project:
  type: website
  output-dir: docs

website:
  title: "Xingjian (Hubery) Tao"
  site-url: "https://hubery-tao.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
  page-footer:
    center: "© 2026 Xingjian Tao"

format:
  html:
    theme:
      - flatly
    css: styles.css
    toc: true
